### ISSUE TITLE
Modals dont work

### ISSUE THREAD

**Issue by walperg** [TiagoSilvaPereira/vemto-issues#393] opened 2022-11-17 03:22 UTC
In Master detail modals don´t open.
Attention: Please use the Discussions page for feature requests or suggestions instead of opening a new issue.

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by TiagoSilvaPereira** [comment] 2022-11-17 12:13
@walperg could you please give more details? Are there errors in the console?

**Comment by TiagoSilvaPereira** [comment] 2022-11-17 14:13
@walperg seems there is a problem with alpine update... we are trying to fix it ASAP

**Comment by walperg** [comment] 2022-11-19 05:36
Not, it only not open the modal windows, not say nothing in console, any idea how can i resolve it?

**Comment by TiagoSilvaPereira** [comment] 2022-11-19 12:31
@walperg yes, please disable Turbo in the project settings... soon we'll launch another Vemto version with Turbo disabled by default

**Comment by walperg** [comment] 2022-11-21 01:12
Thanks, i'm do it, but not working jet, i'm think the issue is livewire/livewire.js not exist

**Comment by TiagoSilvaPereira** [comment] 2022-11-21 12:37
Hi @walperg did you disable Turbo and generated the code again?

**Comment by walperg** [comment] 2022-11-21 12:41
Yes im do it , and see all the things in the page, and not find limeware.js

**Comment by walperg** [comment] 2022-11-21 12:41
Something more , im work in Windows and wamp server

**Comment by TiagoSilvaPereira** [comment] 2022-11-26 12:22
Hi @walperg I did a lot of tests but could not reproduce the bug... did you try generating a different project?

**Comment by walperg** [comment] 2022-11-26 21:48
Yes i'm try, can you send me your settings? thanks!!

**Comment by TiagoSilvaPereira** [comment] 2022-11-28 13:02
Hi @walperg, I tested with standard Vemto settings. I'll close the issue for now, as it seems there is no issue on the Vemto side. Please feel free to keep commenting and sending information here if necessary

**Closed by TiagoSilvaPereira** 2022-11-28 13:02 UTC
