### ISSUE TITLE
Cannot set property 'postcss' of undefined

### ISSUE THREAD

**Issue by gregvarghese** [TiagoSilvaPereira/vemto-issues#254] opened 2021-10-31 18:53 UTC
Attention: Please use the Discussions page for feature requests or suggestions instead of opening a new issue.

**Describe the bug**
When generating code with a new project in 1.0.0.0, I get the errors:
Cannot set property 'postcss' of undefined
TypeError: Cannot set property 'postcss' of undefined at Pe.getFinalPackageFile (app://./js/generator.72eb147b.js:1:35290) at Pe.start (app://./js/generator.72eb147b.js:1:35166) at Et.callProjectGenerators (app://./js/generator.72eb147b.js:1:59628) at async app://./js/generator.72eb147b.js:1:58407 

**To Reproduce**
1. Create a new project
2. Use bootstrap UI instead of tailwind
3. Create a few models
4. Generate code

**Expected behavior**
Working application generates

**Screenshots**
<img width="2216" alt="Screen Shot 2021-10-31 at 2 52 13 PM" src="https://user-images.githubusercontent.com/12222172/139597465-3f38ef9c-022a-4943-a4dc-29fe5a09ec8b.png">

**Desktop (please complete the following information):**
 - OS: MacOS

**Additional context**

**Comment by gregvarghese** [comment] 2021-10-31 18:57
Update: I tested Breeze + Jetstream and it appears this error happens with all of the options.

**Comment by TiagoSilvaPereira** [comment] 2021-11-01 14:25
Hi @gregvarghese I tried to reproduce, but without success...

Could you please check if one of these links helps with this error?

https://github.com/laravel-mix/laravel-mix/issues/2527
https://github.com/webpack-contrib/postcss-loader/issues/65

**Comment by gregvarghese** [comment] 2021-11-12 13:57
Hi @TiagoSilvaPereira , 

I ran npm run production and got the error:

npm ERR! missing script: production

so I checked package.json and it's empty. 

This is a project I created with Vemto and haven't made any updates too. I created a new project to try and reproduce it and I'm getting this error: 

<img width="3159" alt="Screen Shot 2021-11-12 at 8 54 30 AM" src="https://user-images.githubusercontent.com/12222172/141478101-9b932db1-a07f-4d43-95bf-6d3b8a9cb66d.png">

I've attached the project Vemto generated in case it helps 
[vemto_test.zip](https://github.com/TiagoSilvaPereira/vemto-issues/files/7528010/vemto_test.zip)

**Comment by TiagoSilvaPereira** [comment] 2021-11-12 15:34
Hi @gregvarghese this problem is happening because Vemto 1.0.0 has some problems with Laravel 7... I recommend always using Laravel 8.x when creating projects with this Vemto version... I'm fixing these issues and 1.0.1 will support Laravel 7.x again. If you want to use Laravel 7.x, please try Vemto 0.9.x

**Comment by TiagoSilvaPereira** [comment] 2021-12-11 19:59
Fixed on 1.0.1

**Closed by TiagoSilvaPereira** 2021-12-11 19:59 UTC
