### ISSUE TITLE
Jerky screen makes it hard to accurately type fields

### ISSUE THREAD

**Issue by tkerns** [TiagoSilvaPereira/vemto-issues#180] opened 2021-06-29 17:33 UTC
When I edit fields in a table Vemto constantly saves, even between keystrokes, causing the screens to jump around.  There is also perceptible lag, causing letters to lag and sometime be skipped.
This has happening on all versions as far as I can tell.  I have 0.9.7 installed currently.
I am running this on windows 10 on a high end laptop (not underpowered), Alienware Area 51m.

It might be nice to be able to choose when to save instead of saving automatically, and have Vemto remind me to save when I quit if file is not already saved.
Here is a gif showing the issue.  Anybody else have this problem?

![zoom_1](https://user-images.githubusercontent.com/4198125/123842068-d097e980-d8bc-11eb-925a-7534ef3d074a.gif)

**Comment by TiagoSilvaPereira** [comment] 2021-06-30 13:44
Hi @tkerns thank you for reporting, I'll check what is happening

**Comment by tkerns** [comment] 2021-07-06 20:37
@TiagoSilvaPereira I did some more troubleshooting, and the jerkiness appears tied to a windows setting that makes everything bigger.  ie settings > display > make everything bigger (set to 125%).  If I change it back to 100% the jerkiness goes away, BUT there is still a lag when in the schema editor, adding new fields and typing in them, that often causes characters to drop.  Unless I type at a rate of 1 character per second :-)

**Comment by TiagoSilvaPereira** [comment] 2021-07-07 18:46
Hi @tkerns thank you for this information... that is a strange bug, but I suspect the problem is occurring due to the Schema relationships lines rendering. Whenever you change a field, Vemto needs to re-render the Schema, and it is a costly task to the CPU.

Although it looks like (because it is fired by the same event), the problem is probably not with Vemto trying to save the data, as this is done first in RAM, and then asynchronously to disk (so this doesn't cause application lag).

I believe that if I limit the number of times the Schema is rendered, the problem should be solved.

Best regards

**Comment by tkerns** [comment] 2021-07-07 18:58
@TiagoSilvaPereira It appears that it re renders after every keystroke.  I wonder if you could do it when you leave the field (like on blur), or add some sort of debounce like livewire does on field changes, so it doesn't re render after every keystroke.
Thanks for your work on this.  I am really loving this tool!

**Comment by TiagoSilvaPereira** [comment] 2021-07-07 19:01
Hi @tkerns, yeah, I'll add a debounce to the render method... it probably will solve or reduce the problem... typing on the field already has a debounce of 300ms, but I'll change it to something greater

**Comment by ianhawes** [comment] 2021-07-07 19:35
I'm encountering this issue on macOS Big Sur (11.4).

I've noticed that restarting the app seems to solve the issue for a brief period.

**Comment by TiagoSilvaPereira** [comment] 2021-07-07 19:43
Hi @ianHi @ianhawes thank you for sharing... probably the Schema rendering is causing some CPU performance issues or some memory leaks... I'm investigating what is happening to launch a new version fixing that

**Comment by TiagoSilvaPereira** [comment] 2021-07-12 23:55
@tkerns @ianhawes fixed on 0.9.8 (I would love to hear your feedback). Thank you

**Closed by TiagoSilvaPereira** 2021-07-12 23:55 UTC
Labels: important

**Comment by tkerns** [comment] 2021-07-13 01:11
@TiagoSilvaPereira This seems to have fixed the issues with lag and missing letters when typing in a schema field name, thanks!
I still have the jerky screen issue that appears to be due to my windows display setting being set to 125%.  This is a minor annoyance, so no worries there.

**Comment by TiagoSilvaPereira** [comment] 2021-07-13 14:27
@tkerns awesome... I'll try to identify what is happening about the screen issue to fix it on the next version. Best regards
