### ISSUE TITLE
[BUG] Type error admin panel

### ISSUE THREAD

**Issue by ThibautDeMaerteleire** [TiagoSilvaPereira/vemto-issues#101] opened 2021-04-04 08:57 UTC
**Describe the bug**
When I go to the admin panel and login correctly, then click on one of the type/tables/apps it gives this error like in the screenshots. In the default Users table I don't have this problem. I did some testing and the problem/bug is only there if you choose for Bootstrap and the laravel UI template. 

<img width="1535" alt="Screenshot 2021-04-04 at 10 25 18" src="https://user-images.githubusercontent.com/55394748/113503122-1cdac400-9530-11eb-811e-cfa3af2dba8f.png">
<img width="1667" alt="Screenshot 2021-04-04 at 10 24 59" src="https://user-images.githubusercontent.com/55394748/113503130-22d0a500-9530-11eb-9985-9aee04143e5e.png">
<img width="1643" alt="Screenshot 2021-04-04 at 10 24 44" src="https://user-images.githubusercontent.com/55394748/113503132-25cb9580-9530-11eb-9c73-0a938c1f9ef7.png">

**Comment by TiagoSilvaPereira** [comment] 2021-04-04 22:18
Hi @ThibautDeMaerteleire thank you for reporting... could you please send a screenshot of your Schema?

**Comment by ThibautDeMaerteleire** [comment] 2021-04-05 10:15
![Uploading Screenshot 2021-04-05 at 10.57.46.png…]()

**Comment by ThibautDeMaerteleire** [comment] 2021-04-05 10:15
<img width="1416" alt="Screenshot 2021-04-05 at 10 57 46" src="https://user-images.githubusercontent.com/55394748/113563806-a1007a80-9608-11eb-936d-d4c274cf5cb2.png">

**Comment by TiagoSilvaPereira** [comment] 2021-04-05 15:31
Thank you @ThibautDeMaerteleire as I suspected the problem is these **json** columns. I'll add a fix to it for the next Vemto version but, for now, you can remove them from from your index page or treat the way they were printed on the blade files.

Please check this link for reference: https://stackoverflow.com/questions/43217872/laravel-htmlspecialchars-expects-parameter-1-to-be-string-object-given

**Comment by TiagoSilvaPereira** [comment] 2021-04-06 21:28
@ThibautDeMaerteleire fixed on version **0.8.2**

**Closed by TiagoSilvaPereira** 2021-04-06 21:28 UTC
Labels: bug
