### ISSUE TITLE
[BUG] Cannot edit CRUD Form Settings

### ISSUE THREAD

**Issue by relayer464** [TiagoSilvaPereira/vemto-issues#52] opened 2020-12-18 03:05 UTC
**Describe the bug**
While working with CRUD form settings, they periodically freeze and I cannot change any Form Settings.

**To Reproduce**
1. Go to Project Apps
2. Click on a previously created CRUD app
3. Start modifying various Components, including Settings
4. Usually everything works as expected, but then eventually the Settings freeze so you can change any of them.
5. If I close Vemto and restart it a bit later I can access the Form Settings again.

Note: I have not been able to determine what is the trigger or event that happens just prior to the Settings freezing.

**Expected behavior**
I would expect the Form Settings to be editable all the time, but they seem to randomly freeze.

**Screenshots**
I will try to add a video of this behavior the next time it happens.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Browser: Chrome
 - Vemto v.0.6.2

**Comment by TiagoSilvaPereira** [comment] 2020-12-18 21:10
Hi @relayer464 thank you for reporting, I'll check it

**Comment by TiagoSilvaPereira** [comment] 2020-12-22 15:44
@relayer464 I could not reproduce this problem... is it occurring with all your projects or with a specific one?

**Comment by relayer464** [comment] 2020-12-23 18:43
Yes, this problem appears to occur on other projects.

However, I think I may have discovered the triggering event (or at least one of them).  It seems to happen after I've deleted a CRUD form field.  For example, say I have a Text input and I want to change it to a Select.  If I delete the Text input, that seems to be when the Settings freeze.

**Comment by TiagoSilvaPereira** [comment] 2021-01-13 15:26
@relayer464 I tried to identify the problem but still could not reproduce the problem... Could you please send a small video showing the issue? Thank you

**Comment by TiagoSilvaPereira** [comment] 2021-02-11 01:42
@relayer464 fixed on 0.7.3

**Closed by TiagoSilvaPereira** 2021-02-11 01:42 UTC
Labels: bug
