### ISSUE TITLE
[BUG] Can create an entity when entity name in singular form end with an s

### ISSUE THREAD

**Issue by Gallyan** [TiagoSilvaPereira/vemto-issues#90] opened 2021-03-18 20:25 UTC
**Describe the bug**
For example, try to create an entity with entity name: news
You can't create. Error message: The model name needs to be singular.
It's a good warning, but it should be bypassable.

**Expected behavior**
Only a warning.

**Screenshots**
![Capture du 2021-03-18 21-15-57](https://user-images.githubusercontent.com/1420870/111692887-40172b00-8830-11eb-9a01-b72b1e80daa6.png)

**Comment by TiagoSilvaPereira** [comment] 2021-03-18 20:59
Hi @Gallyan thank you for reporting... I'll close it as it is a duplicate of https://github.com/TiagoSilvaPereira/vemto-issues/issues/77

The next version will fix this bug :rocket:

**Closed by TiagoSilvaPereira** 2021-03-18 20:59 UTC
