### ISSUE TITLE
Since the update there is a problem writing with the web file

### ISSUE THREAD

**Issue by jim1506** [TiagoSilvaPereira/vemto-issues#155] opened 2021-05-30 20:27 UTC
I am using version 0.9.3 on Windows 10.
 There is a problem generating the web.php. I have just generated a new project and the web file had only home generated, even though I had marked several apps to be generated.

Also it is not running automaticall php artisan serve on the run.

**Comment by TiagoSilvaPereira** [comment] 2021-05-31 12:50
Hi @jim1506 could you please share more details about the project? Please check if it is skipping files on Code Generation... I tried to reproduce here but it worked well with my project

**Comment by TiagoSilvaPereira** [comment] 2021-06-02 19:33
Hi @jim1506 please check if the default generation options are marked, maybe it is causing the problem related above:
![image](https://user-images.githubusercontent.com/11933789/120541463-4abd7700-c3c0-11eb-87a9-7b990c1a8677.png)

**Comment by jim1506** [comment] 2021-06-03 09:31
OK. I made a new very simple site with just 2 tables:

![2021-06-03_10-20-06](https://user-images.githubusercontent.com/123184/120621895-3c219f00-c456-11eb-925d-fbcee29fec9f.png)

This is Laravel 8 with Tailwind and the Laravel UI authentication

When I compiled this I noticed:

![2021-06-03_10-12-45](https://user-images.githubusercontent.com/123184/120622040-5e1b2180-c456-11eb-904f-509192ace4d3.png)

and at the end of the compilation the following message:

![2021-06-03_10-18-13](https://user-images.githubusercontent.com/123184/120622167-7b4ff000-c456-11eb-9d8c-003e3edfbe37.png)

and I had defined two apps:

![2021-06-03_10-20-25](https://user-images.githubusercontent.com/123184/120622262-8e62c000-c456-11eb-938c-b04c07f330cb.png)

At the end of the compilation I got

![2021-06-03_10-18-47](https://user-images.githubusercontent.com/123184/120622367-a5091700-c456-11eb-9c11-4b4b3d0e2021.png)

php artisan server was not launched so I got

![2021-06-03_10-21-32](https://user-images.githubusercontent.com/123184/120622476-c0742200-c456-11eb-904d-a7ecaef8c680.png)

and the generation caused an error:

![2021-06-03_10-23-07](https://user-images.githubusercontent.com/123184/120622531-ce29a780-c456-11eb-87c2-e218bbc6104b.png)

**Comment by TiagoSilvaPereira** [comment] 2021-06-03 14:39
Hi @jim1506 when Vemto skips a file, it is because it was changed on your Disk by another software (maybe the OS) or manually... in that case, just click on the **Compare Diff** option and **overwrite the file**... it forces overwriting the file with the Vemto version and now Vemto can track the changes and write to that file normally.

About Vemto not running *php artisan serve*, and the permissions problem, it is because the command *php artisan migrate:fresh --seed* did not run correctly... In that case, it is necessary to run it manually to check what problem you have with your schema (in the majority of the cases, it is caused because you forgot to add a nullable clause to a foreign key).

Just fix the schema and run it again.

**Comment by TiagoSilvaPereira** [comment] 2021-06-25 21:26
Hi @jim1506 I'm closing it for now, as it seems to not be a Vemto bug. If you have any questions, please feel free to contact me

**Closed by TiagoSilvaPereira** 2021-06-25 21:26 UTC
