### ISSUE TITLE
Missing field "two factor secret" in Jetstream installation

### ISSUE THREAD

**Issue by martin-masterclass** [TiagoSilvaPereira/vemto-issues#299] opened 2022-04-18 15:18 UTC
Hi Tiago, I just created a Jetstream Installation with only an User app.
When I click on "Profile" then I get an error because a field is missing in users table. Regards, Martin

<img width="270" alt="image" src="https://user-images.githubusercontent.com/64164118/163829834-86375798-704e-4d3b-b2a6-dfe0ab71937e.png">
<img width="923" alt="image" src="https://user-images.githubusercontent.com/64164118/163829934-e6582f90-f5fa-488a-af5e-5169a82976ff.png">

**Comment by TiagoSilvaPereira** [comment] 2022-04-18 16:05
Hi @martin-masterclass ,

It is due to a change to the latest Jetstream version. I'll fix it for the next Vemto version, but you can easily fix it by adding the field two_factor_confirmed_at (timestamp, NULLABLE) to the User model:

![1 (1)](https://user-images.githubusercontent.com/11933789/163836823-c1b67edc-db9f-401a-ac14-a1ad63a868cc.png)

**Comment by martin-masterclass** [comment] 2022-04-18 17:51
Hi Tiago, I'm aware that it is not a big thing, I just think this little thing should work if you sell the yearly membership for $79.
This is no criticism, I know it must be hard to program an app like this, and you seem to have not so much help from others.

I think you need some marketing for your app.
I emailed you on Apr. 16th, for a business proposal to “contact@vemto.app”. (In Portuguese)

Not only that, but I am a No.1 Laravel Instructor on Udemy and now, my question is, if I should recommend your app to my 10,000+ Laravel students and make a special course about Vemto.

If you like, we can talk more.

Best regards, Martin

**Comment by TiagoSilvaPereira** [comment] 2022-04-18 18:29
Hi @martin-masterclass it is not working yet because Jetstrem just added this new database field... as Jetstream is a technology by the Laravel team, I need to wait for them to launch changes like this, and then I can launch a Vemto version fixing it (that I hope to launch this week).

About the partnership, thanks, I'll analyze the proposal and get in contact asap.

Best regards

**Comment by martin-masterclass** [comment] 2022-04-18 18:40
Tudo bem, obrigado, até logo.

**Comment by Benoit1980** [comment] 2022-04-23 19:01
Same problem here. I just tried it on version 1.1.3, Thanks Tiago.

**Comment by TiagoSilvaPereira** [comment] 2022-04-24 10:07
Fixed on 1.1.3 for new projects

@Benoit1980 if you are having this problem in a project created on old Vemto versions, please adopt the solution I wrote above:

> Hi @martin-masterclass ,
> 
> It is due to a change to the latest Jetstream version. I'll fix it for the next Vemto version, but you can easily fix it by adding the field two_factor_confirmed_at (timestamp, NULLABLE) to the User model:
> 
> ![1 (1)](https://user-images.githubusercontent.com/11933789/163836823-c1b67edc-db9f-401a-ac14-a1ad63a868cc.png)

**Closed by TiagoSilvaPereira** 2022-04-24 10:07 UTC

**Comment by Benoit1980** [comment] 2022-04-24 18:21
Thanks @TiagoSilvaPereira !
