### ISSUE TITLE
CSS recommendation for required fields

### ISSUE THREAD

**Issue by henriquek3** [TiagoSilvaPereira/vemto-issues#219] opened 2021-08-21 21:04 UTC
Increment this CSS snippet to put a red * on the field labels that are required

```css
.label-required:after {
    content: " *";
    color: red;
}
```

**Comment by TiagoSilvaPereira** [comment] 2021-08-23 14:21
Hi @henriquek3 thank you for your suggestion... I'm moving it to **Discussions** as it is not a bug

**Closed** 2021-08-23 14:21 UTC
