### ISSUE TITLE
Filament Resources not generated when "Auth Scaffold with Jetstream" is selected

### ISSUE THREAD

**Issue by drese** [TiagoSilvaPereira/vemto-issues#402] opened 2022-12-17 14:31 UTC
When the "Auth Scaffold with Jetstream" option is selected, the 'Filament' directory and the nested resources, filters and traits are not generated. When not selected, they are created as expected.

**Comment by cnngraphics** [comment] 2023-01-10 18:53
Same issue for me.

**Comment by hubciorz** [comment] 2023-01-18 13:56
@TiagoSilvaPereira @nicollassilva Any news? Jetstream + Filament is also my setup :(

**Comment by TiagoSilvaPereira** [comment] 2023-01-18 14:43
@hubciorz @cnngraphics @drese, what version of the Filament plugin are you currently using?

**Comment by TiagoSilvaPereira** [comment] 2023-01-18 18:08
@hubciorz @cnngraphics @drese, could you please share your project file (.vemto) to email contact@vemto.app? Also, please check if you are using the latest Vemto and plugin versions. We tried to reproduce the issue, but without success

**Comment by TiagoSilvaPereira** [comment] 2023-02-22 14:03
Closing due to lack of details... please check if your Filament plugins are upgraded to the lastest version

**Closed by TiagoSilvaPereira** 2023-02-22 14:03 UTC
