### ISSUE TITLE
Problem when trying to delete any field

### ISSUE THREAD

**Issue by AlanKurdish** [TiagoSilvaPereira/vemto-issues#152] opened 2021-05-21 22:45 UTC
**Describe the bug**
when i delete any item the program get lagged and i cannot write any other word in any field 
**To Reproduce**
1. Go to Schema editor
2. Create Schema
3. Delete schema
4. Try to create or edit any field you wonnt be able to write mouse cursor disappear

**Expected behavior**
the cursor shouldnot disappear after deleting an item and it should work 

**Screenshots**
![Screenshot (35)](https://user-images.githubusercontent.com/48416539/119204897-6317c280-ba9f-11eb-996e-a33f487ee25f.png)

**Comment by TiagoSilvaPereira** [comment] 2021-05-24 13:02
Hi @AlanKurdish thank you for reporting

Sorry I did not understand... what type of item (entity, field, relationship, etc) you deleted before Vemto throwing the error?

**Comment by TiagoSilvaPereira** [comment] 2021-05-25 14:18
Hi @AlanKurdish could you please share more details?

**Comment by AlanKurdish** [comment] 2021-05-26 15:59
When deleting any type of element it throw error the cursor disappear and you cannot use the program again

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by TiagoSilvaPereira** [comment] 2021-05-31 12:52
Hi @AlanKurdish could you try reinstalling Vemto? Seems it is having some incompatibilities with your OS

**Comment by TiagoSilvaPereira** [comment] 2021-06-02 19:31
Hi @AlanKurdish  I tried to reproduce the error, but it doesn't happen here... could you please record a short video showing the process you are doing before throwing the error? Thanks

**Comment by TiagoSilvaPereira** [comment] 2021-06-18 20:21
Closing as I would not able to reproduce... please open the issue again if necessary.

**Closed by TiagoSilvaPereira** 2021-06-18 20:21 UTC
