### ISSUE TITLE
[BUG] Flashing Scrollbars

### ISSUE THREAD

**Issue by blackfyre** [TiagoSilvaPereira/vemto-issues#195] opened 2021-07-13 06:00 UTC
**Describe the bug**
On Windows 10, when opening a table for editing the spinner on the bottom bar causes the scrollbars to flash, and the resulting shift in the horizontal space makes things harder to interact with, and especially annoying when typing.

**To Reproduce**
1. Go to schema editor
2. Click on random table
3. Interact

**Expected behavior**
I would not expect the scrollbar to flash. It should either stay hidden or be always visible.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: N/A (Electron/Chrome)
 - Version: all, up to 0.9.8

**Additional context**
The short debounce after the last action bites back as well when typing out the column names as well.

https://youtu.be/c6cGnk84n2Y

**Comment by TiagoSilvaPereira** [comment] 2021-07-13 14:26
Hi @blackfyre thank you for reporting... could you please check if there is something related to #180 (seems like this scrollbar flash is caused by zoom issues on Windows OS)

**Comment by blackfyre** [comment] 2021-07-13 14:44
Will do, asap 😊

**Comment by blackfyre** [comment] 2021-07-13 21:10
Soo... The magnification which is 125% by default on windows for a 15.6 screen with a 1920x1080 resolution is definitely related to the problem.
But, reducing the scaling to 100% isn't an ideal solution, with the screen above it causes too much strain on the eyes. 
I'm happy to help debug this issue further!

**Comment by TiagoSilvaPereira** [comment] 2021-07-14 14:03
@blackfyre thank you, I'll try to fix it for the next version

**Comment by HRR1337** [comment] 2021-08-11 17:25
This is the first thing I also wanted to report. It makes me a bit nauseous.

**Comment by TiagoSilvaPereira** [comment] 2021-08-12 14:18
Hi @HRR1337 unhappiness I did not found a solution for this yet but seems like it is happening on Windows due to zoom issues, as you can see here: #180

Could you please check if the zoom is what is causing the problem in your case too?

**Comment by blackfyre** [comment] 2021-08-13 06:40
@TiagoSilvaPereira what kind of height units are you using? `px`? `em`? `rem`?

**Comment by HRR1337** [comment] 2021-08-13 07:43
My screen is on 150%, and then it flickers. I have tested it on 100% and then the screen is not flickering (no scrollbar when the system saves something).

**Comment by TiagoSilvaPereira** [comment] 2021-08-13 13:58
@blackfyre it is using **rem**

**Comment by blackfyre** [comment] 2021-08-13 17:56
Then my only guess is to blame the icon and it's animation... Probably the icon's bounding box pushes the container apart... A hidden overflow on the icon's container might do the trick...

**Comment by TiagoSilvaPereira** [comment] 2021-08-14 15:56
Hi @blackfyre thank you for your suggestion... I'll check it asap

**Comment by TiagoSilvaPereira** [comment] 2021-08-21 17:16
@blackfyre @HRR1337 @tkerns fixed on  0.9.10

**Closed by TiagoSilvaPereira** 2021-08-21 17:16 UTC
Labels: important

**Comment by blackfyre** [comment] 2021-08-23 06:52
Can confirm, problem solved!
Thanks @TiagoSilvaPereira!
