### ISSUE TITLE
[BUG] Foreign key listed twice in model factory

### ISSUE THREAD

**Issue by CrixuAMG** [TiagoSilvaPereira/vemto-issues#21] opened 2020-10-31 09:42 UTC
**Describe the bug**
After creating an entity that belongs to another entity via a foreign key, the foreign key (user_id for example) is listed twice in the entities' factory. 

**To Reproduce**
See description above.

**Expected behavior**
The key should not be listed twice

**Screenshots**
[https://imgur.com/a/nXDFGsx](https://imgur.com/a/nXDFGsx)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version v0.5.3

Let me know if you need any other information!

**Comment by TiagoSilvaPereira** [comment] 2020-10-31 15:12
Hi @CrixuAMG thank you for reporting it... could you please send a Schema screenshot so I can reproduce the issue here? Cheers

**Comment by CrixuAMG** [comment] 2020-10-31 15:37
Hey Tiago,

Sure, here's a link. Let me know if you need anything else!

[https://imgur.com/a/XcEyeC6](https://imgur.com/a/XcEyeC6)

**Comment by TiagoSilvaPereira** [comment] 2020-11-02 19:06
Hi @CrixuAMG I just tried it but I could not reproduce the issue... could you check if the issue continues even after generating the code again?

![image](https://user-images.githubusercontent.com/11933789/97908218-29f74b00-1d25-11eb-8576-5662a69bcf4f.png)
![image](https://user-images.githubusercontent.com/11933789/97908294-42fffc00-1d25-11eb-9b14-157f4580a9b9.png)

**Comment by CrixuAMG** [comment] 2020-11-02 20:07
Hi @TiagoSilvaPereira,

I tried it again, the main difference I noted after it occurring again is that my user_id field in Vemto is of type Foreign ID. Maybe this has something to do with the way the keys are generated in the model factory?

**Comment by TiagoSilvaPereira** [comment] 2020-11-02 20:44
Oh yeah!! Thank you, bro, that was the problem... I wasn't noticing it because I generally don't add the Foreign manually, I just create the relationship and let Vemto create it automatically, but it always creates as "Unsigned Big Integer". Changing to "ForeignId" I was able to reproduce and fix the problem. 

I'll close the issue once I launch the next version.

Cheers!

**Comment by CrixuAMG** [comment] 2020-11-02 20:48
No problem!

Also, I am working on getting my new colleagues excited on getting Vemto licenses. 😉

**Comment by TiagoSilvaPereira** [comment] 2020-11-02 22:32
Awesome to know that :smile: I just launched Vemto 0.5.5 with these fixes. If you have another issue, please feel free to open another issue. Thank your bro, have a nice day.

**Closed by TiagoSilvaPereira** 2020-11-02 22:32 UTC
Labels: bug
